spring.application.name=pikafast
spring.datasource.url=jdbc:mysql://localhost:3306/pikafast

spring.datasource.username=root

spring.datasource.password=Nieves300305

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true